name: Generate Logos Manifest

on:
  push:
    paths:
      - 'countries/**/*.png'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Generate manifest
        run: python3 generate_manifest.py
        
      - name: Commit manifest
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add logos-manifest.json
          git diff --staged --quiet || git commit -m "Auto-generate logos manifest"
          git push
